import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:provider/provider.dart';
import 'package:go_router/go_router.dart';
import 'package:intl/intl.dart';
import 'package:tb_notification_tracker/widgets/app_scaffold.dart';
import 'package:tb_notification_tracker/providers/auth_provider.dart';
import 'package:tb_notification_tracker/repositories/case_repository.dart';
import 'package:tb_notification_tracker/models/case_model.dart';

/// Case entry screen for PHC users
class CaseEntryScreen extends StatefulWidget {
  const CaseEntryScreen({super.key});

  @override
  State<CaseEntryScreen> createState() => _CaseEntryScreenState();
}

class _CaseEntryScreenState extends State<CaseEntryScreen> {
  final _formKey = GlobalKey<FormState>();
  final _patientNameController = TextEditingController();
  final _patientAgeController = TextEditingController();
  final _phoneNumberController = TextEditingController();
  
  Gender _selectedGender = Gender.male;
  bool _isSubmitting = false;
  final DateTime _createdAt = DateTime.now();

  @override
  void dispose() {
    _patientNameController.dispose();
    _patientAgeController.dispose();
    _phoneNumberController.dispose();
    super.dispose();
  }

  Future<void> _submitCase() async {
    // Validate form
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() {
      _isSubmitting = true;
    });

    try {
      final authProvider = context.read<AuthStateProvider>();
      final currentUser = authProvider.currentUserData;

      if (currentUser == null) {
        throw Exception('User not authenticated');
      }

      // Create case model
      final caseModel = CaseModel(
        caseId: '', // Will be generated by repository
        phcName: currentUser.phcName,
        createdByUserId: currentUser.userId,
        createdAt: _createdAt,
        patientName: _patientNameController.text.trim(),
        patientAge: int.parse(_patientAgeController.text.trim()),
        patientGender: _selectedGender,
        phoneNumber: _phoneNumberController.text.trim(),
        caseStatus: CaseStatus.processing, // Default status
      );

      // Validate case data
      if (!caseModel.isValid()) {
        throw Exception('Invalid case data');
      }

      // Create case in Firestore
      final caseRepository = FirestoreCaseRepository();
      await caseRepository.createCase(caseModel);

      if (!mounted) return;

      // Show success message
      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: const Text('Case created successfully'),
          backgroundColor: Theme.of(context).colorScheme.primary,
          action: SnackBarAction(
            label: 'View Cases',
            textColor: Colors.white,
            onPressed: () {
              context.go('/case-list');
            },
          ),
        ),
      );

      // Clear form
      _patientNameController.clear();
      _patientAgeController.clear();
      _phoneNumberController.clear();
      setState(() {
        _selectedGender = Gender.male;
      });
    } catch (e) {
      if (!mounted) return;

      ScaffoldMessenger.of(context).showSnackBar(
        SnackBar(
          content: Text('Failed to create case: $e'),
          backgroundColor: Theme.of(context).colorScheme.error,
        ),
      );
    } finally {
      if (mounted) {
        setState(() {
          _isSubmitting = false;
        });
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    final authProvider = context.watch<AuthStateProvider>();
    final currentUser = authProvider.currentUserData;

    if (currentUser == null) {
      return const AppScaffold(
        title: 'Case Entry',
        child: Center(
          child: Text('User not authenticated'),
        ),
      );
    }

    final dateFormat = DateFormat('dd/MM/yyyy HH:mm');

    return AppScaffold(
      title: 'Case Entry',
      child: SingleChildScrollView(
        padding: const EdgeInsets.all(24.0),
        child: Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 600),
            child: Card(
              elevation: 1,
              child: Padding(
                padding: const EdgeInsets.all(24.0),
                child: Form(
                  key: _formKey,
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.stretch,
                    children: [
                      // Header
                      Text(
                        'New TB Case Entry',
                        style: Theme.of(context).textTheme.headlineSmall,
                      ),
                      const SizedBox(height: 8),
                      Text(
                        'Enter patient information for TB notification',
                        style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                              color: Theme.of(context).colorScheme.onSurfaceVariant,
                            ),
                      ),
                      const SizedBox(height: 24),

                      // PHC Name (read-only, auto-filled)
                      TextFormField(
                        initialValue: currentUser.phcName,
                        decoration: const InputDecoration(
                          labelText: 'PHC Name',
                          prefixIcon: Icon(Icons.local_hospital),
                          border: OutlineInputBorder(),
                          filled: true,
                        ),
                        readOnly: true,
                        enabled: false,
                      ),
                      const SizedBox(height: 16),

                      // Date and Time (read-only, auto-filled)
                      TextFormField(
                        initialValue: dateFormat.format(_createdAt),
                        decoration: const InputDecoration(
                          labelText: 'Date and Time',
                          prefixIcon: Icon(Icons.calendar_today),
                          border: OutlineInputBorder(),
                          filled: true,
                        ),
                        readOnly: true,
                        enabled: false,
                      ),
                      const SizedBox(height: 24),

                      // Patient Name
                      TextFormField(
                        controller: _patientNameController,
                        decoration: const InputDecoration(
                          labelText: 'Patient Name *',
                          prefixIcon: Icon(Icons.person),
                          border: OutlineInputBorder(),
                        ),
                        textCapitalization: TextCapitalization.words,
                        validator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please enter patient name';
                          }
                          return null;
                        },
                      ),
                      const SizedBox(height: 16),

                      // Patient Age
                      TextFormField(
                        controller: _patientAgeController,
                        decoration: const InputDecoration(
                          labelText: 'Patient Age *',
                          prefixIcon: Icon(Icons.cake),
                          border: OutlineInputBorder(),
                          helperText: 'Age must be between 0 and 120',
                        ),
                        keyboardType: TextInputType.number,
                        inputFormatters: [
                          FilteringTextInputFormatter.digitsOnly,
                        ],
                        validator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please enter patient age';
                          }
                          final age = int.tryParse(value.trim());
                          if (age == null) {
                            return 'Please enter a valid number';
                          }
                          if (age < 0 || age > 120) {
                            return 'Age must be between 0 and 120';
                          }
                          return null;
                        },
                      ),
                      const SizedBox(height: 16),

                      // Patient Gender
                      DropdownButtonFormField<Gender>(
                        initialValue: _selectedGender,
                        decoration: const InputDecoration(
                          labelText: 'Patient Gender *',
                          prefixIcon: Icon(Icons.wc),
                          border: OutlineInputBorder(),
                        ),
                        items: Gender.values.map((gender) {
                          return DropdownMenuItem(
                            value: gender,
                            child: Text(gender.value),
                          );
                        }).toList(),
                        onChanged: (value) {
                          if (value != null) {
                            setState(() {
                              _selectedGender = value;
                            });
                          }
                        },
                      ),
                      const SizedBox(height: 16),

                      // Phone Number
                      TextFormField(
                        controller: _phoneNumberController,
                        decoration: const InputDecoration(
                          labelText: 'Phone Number *',
                          prefixIcon: Icon(Icons.phone),
                          border: OutlineInputBorder(),
                          helperText: '10-digit mobile number',
                        ),
                        keyboardType: TextInputType.phone,
                        inputFormatters: [
                          FilteringTextInputFormatter.digitsOnly,
                          LengthLimitingTextInputFormatter(10),
                        ],
                        validator: (value) {
                          if (value == null || value.trim().isEmpty) {
                            return 'Please enter phone number';
                          }
                          final cleaned = value.replaceAll(RegExp(r'[\s\-\(\)]'), '');
                          if (!RegExp(r'^\d{10}$').hasMatch(cleaned)) {
                            return 'Please enter a valid 10-digit number';
                          }
                          return null;
                        },
                      ),
                      const SizedBox(height: 24),

                      // Submit Button
                      FilledButton(
                        onPressed: _isSubmitting ? null : _submitCase,
                        child: Padding(
                          padding: const EdgeInsets.symmetric(vertical: 12.0),
                          child: _isSubmitting
                              ? const SizedBox(
                                  height: 20,
                                  width: 20,
                                  child: CircularProgressIndicator(
                                    strokeWidth: 2,
                                  ),
                                )
                              : const Text('Submit Case'),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ),
      ),
    );
  }
}
