// This file is auto-generated by Flutter build process
// Service worker for offline caching
// The Flutter build process will generate the actual service worker content
// This is a placeholder that will be replaced during build

'use strict';

const CACHE_NAME = 'tb-tracker-cache-v1';
const RESOURCES = {};

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((cacheNames) => {
      return Promise.all(
        cacheNames.map((cacheName) => {
          if (cacheName !== CACHE_NAME) {
            return caches.delete(cacheName);
          }
        })
      );
    })
  );
});

self.addEventListener('fetch', (event) => {
  event.respondWith(
    caches.match(event.request).then((response) => {
      return response || fetch(event.request);
    })
  );
});
